language: java
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: Unit Tests
      script: ./mvnw test -P development
    - stage: Integration Tests
      script: ./mvnw integration-test -P integration-tests