sudo: false
language: java
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2"


addons:
  sonarcloud:
    organization: joufa-github
    token:
      secure: "0LlCsTw3sPmUxG7RHYQ+qko9I+fzsckXp4AL5KlgoHNCeLGBvujhYHAffyUyQ4LlCDA2Gbidv1eN1HD00gklNP1zumQyqa6g3Wubov4VHPwUcF2gG+zNv4BJKC/flJ553FsYqit4Z5Xbd88py055P6osHu/4HSQ3RhMvOsnBemBspqjKSgfMoi9LGVUXI6zMNfRJgsITuv0JfQ/z+6G8ZOWhWlhpwuIf8QmKqKBBXfigKN+l3hWlwjd89IrO4y++UbE6cgUbiso+Y4vdb9O7qUC5I4bbD+CGrU7Eg6Wl/NyhvwNvR+K/Llt2SvvGfyPeITjWNyuUo+l2lTpV0Aoi5H9v0rhuDsp9SnqYjuYsaPxJmQPsiMqzcRsjCiejL1SLsJ6qyN4g45lNxA04H5AbOPcVKzPEaq0Q9hwAiLouDBQvJtA+V90FyzHcVw8yoFDYxOdu4G5IBZDthpOf19z9qKB9G0WhQMP/P36Q/uJY7hxEsn7BgZmmQ0LN+ZN0lltN9Xxg6EVg9tfW/WFMtvP2F+WkwopTh65jX+LzuFPNC+IwyQviAvyIUbYfVHIBFsIW4VZV9yGz8/cD84Nq6x4Af6dCkrbeoyJsgcfnZ0zwIgJUAX/NHWiiEEQNmQ2YmlzGf6CF/i4mEgQx2OUdbo0KhsmKJkCdX6tpK4WTl7ji7ac="
jobs:
  include:
    - stage: Tests
      name: Integration tests
      script: "./mvnw integration-test -P integration-tests"
    - stage: Coverage
      script: "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar"