spring:
  profiles:
    active: @activatedProperties@
  main:
    banner-mode: "off"
---
spring:
  profiles: development
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

---
spring:
  profiles: production
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    # The following disables an exception referenced here:
    # https://vkuzel.blogspot.in/2016/03/spring-boot-jpa-hibernate-atomikos.html
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect